### ISSUE TITLE
支持Animator Controller的实时GPU蒙皮 这篇文章有demo 吗

### ISSUE THREAD

**Issue by sosloop** [zznewclear13/zznewclear13.github.io#1]

**Comment by zznewclear13** [comment]
你看看这个能不能用吧，时间有点久了。[zznewclear13_GPUSkinning.unitypackage](https://github.com/zznewclear13/zznewclear13.github.io/blob/b70a79d4e14204db14189777447e6a01f73b7a9a/zznewclear13_GPUSkinning.unitypackage)
